import mongoose from "mongoose";

const exam_schema = new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    subject:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Subject",
        required:true,
    },
    program:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Program",
        required:true,
    },
    passMark:{
        type:Number,
        required:true,
        default:50
    },
    totalMark:{
        type:Number,
        required:true,
        default:100
    },
    duration:{
        type:String,
        required:true,
        default:'30 minutes'
    },
    examDate:{
        type:Date,
        required:true,
    },
    examTime:{
        type:String,
        required:true,
        default:'Quiz'
    },
    examStatus:{
        type:String,
        required:true,
        default:'pending',
        enum:['pending','live']
    },
    questions:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'Question',
        }
    ],
    classLevel:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Question',
        required:true
    },
    createdBy:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Professors",
        required:true,
    },
    academicTerm:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"AcademicTerm",
        required:true,
    },
    academicYear:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"AcademicYear",
        required:true,
    }
},
{
    timestamps:true,
})

const Exam = mongoose.model('Exam',exam_schema);
export default Exam;